const TEAM_DATA = [
  {
    id: 'caoxinde',
    name: '曹心德',
    nameEn: 'Cao Xinde',
    role: '课题组负责人',
    title: '特聘教授（二级）',
    category: 'faculty',
    image: 'caoxinde.jpeg',
    email: 'xinde.cao@sjtu.edu.cn',
    research: [
      '土壤地下水污染修复技术及应用',
      '土壤地下水环境多介质界面传输',
      '土壤生物炭固碳及生态环境效应',
      '绿色友好型环境多功能修复材料'
    ],
    bio: '上海交通大学特聘教授（二级）、博士生导师，上海市级环境科学与工程实验教学中心主任，土壤与地下水污染修复技术研究所所长。先后担任环境科学与工程学院副院长、常务副院长、党委书记。国务院政府特殊津贴专家，上海市"浦江人才"计划获得者，全球高被引科学家、中国高被引学者。长期致力于土壤地下水污染修复技术研发及应用、土壤地下水环境多介质界面传输与模拟、土壤生物炭固碳技术及生态环境效应、固废基绿色低碳环境材料创制及应用等方面的研究。主持国家自然科学基金重点项目/面上项目、国家重大专项/重点研发计划课题等项目20多项，在 Nat. Commun., Nat. Rev. Earth Environ., Sci. Bull., Environ. Sci. Technol., Water Res. 等期刊发表 SCI 论文 230 多篇，授权发明专利 12 件。获教育部自然科学一等奖、上海市科技进步一等奖等省部级奖 4 项。',
    education: ['1998-07：中国科学技术大学，博士'],
    courses: ['《土壤污染控制及修复工程》', '《环境化学原理》', '《高等环境化学》'],
    honors: [
      '2024年 国务院政府特殊津贴',
      '2021年 上海交通大学"教书育人奖"个人一等奖',
      '2018年 上海市教学成果二等奖（排名第一）',
      '2016年 上海交通大学教学成果特等奖（排名第一）',
      '2011年 上海市"浦江人才"计划获得者',
      '2003年 教育部自然科学一等奖（排名第三）'
    ]
  },
  {
    id: 'xuxiaoyun',
    name: '续晓云',
    nameEn: 'Xu Xiaoyun',
    role: '研究员',
    title: '研究员',
    category: 'faculty',
    image: 'xuxiaoyun.png',
    email: 'xiaoyun.xu@sjtu.edu.cn',
    research: [
      '土壤界面化学过程及效应',
      '重金属生物地球化学行为',
      '环境功能材料研发及污染土壤修复'
    ],
    bio: '上海交通大学环境科学与工程学院研究员，博士生导师。主要研究方向为土壤界面化学过程及效应、重金属生物地球化学行为、环境功能材料研发及污染土壤修复。在 Environmental Science & Technology、Water Research 等期刊发表多篇高水平论文，参与多项国家自然科学基金及国家重点研发计划课题。',
    education: [],
    courses: ['《高等环境化学》'],
    honors: []
  },
  {
    id: 'qiuhao',
    name: '仇浩',
    nameEn: 'Qiu Hao',
    role: '教授',
    title: '教授',
    category: 'faculty',
    image: 'qiuhao.png',
    email: 'hao.qiu@sjtu.edu.cn',
    research: [
      '土壤地下水污染物迁移转化与归趋模拟',
      '土壤地下水污染风险评估、管控与修复',
      '新污染物（微纳米塑料、稀土）环境与人体健康效应',
      '金属元素及其纳米颗粒生态毒理学效应与机制',
      '全球尺度新污染物空间分布地理格局与驱动机制'
    ],
    bio: '上海交通大学环境科学与工程学院教授，博士生导师。主要研究土壤地下水污染物迁移转化与归趋模拟、污染风险评估与修复，以及新污染物环境与人体健康效应。在 Science Bulletin、Environmental Science & Technology、Water Research 等期刊发表系列研究成果，主持多项国家级科研项目。',
    education: [],
    courses: ['《土壤地下水污染修复》'],
    honors: []
  },
  {
    id: 'zhaoling',
    name: '赵玲',
    nameEn: 'Zhao Ling',
    role: '研究员',
    title: '研究员',
    category: 'faculty',
    image: 'zhaoling.png',
    email: 'ling.zhao@sjtu.edu.cn',
    research: [
      '土壤-地下水污染修复、土壤改良和固碳',
      '生物炭环境功能材料研发和应用',
      '多源固废的低碳协同处理处置'
    ],
    bio: '上海交通大学环境科学与工程学院研究员，博士生导师。主要从事土壤-地下水污染修复、土壤改良和固碳，生物炭环境功能材料研发和应用，以及多源固废的低碳协同处理处置研究。在 Water Research、Environmental Science & Technology、Journal of Hazardous Materials 等期刊发表多篇论文。',
    education: [],
    courses: ['《环境土壤学》', '《土壤-地下水污染修复工程》', '《环境与可持续发展》', '《环境学导论》', '《环境工程大实验》'],
    honors: []
  },
  {
    id: 'liangjun',
    name: '梁峻',
    nameEn: 'Liang Jun',
    role: '助理研究员',
    title: '助理研究员',
    category: 'faculty',
    image: 'liangjun.png',
    email: 'jun.liang@sjtu.edu.cn',
    research: [
      '土壤有机污染过程理论',
      '土壤有机污染修复技术'
    ],
    bio: '上海交通大学环境科学与工程学院助理研究员。主要研究土壤有机污染过程理论及土壤有机污染修复技术，重点关注过硫酸盐高级氧化等非自由基降解路径。在 Environmental Science & Technology、Applied Catalysis B-Environmental 等期刊发表多篇论文。',
    education: [],
    courses: [],
    honors: []
  },
  {
    id: 'yanlijun',
    name: '严立俊',
    nameEn: 'Yan Lijun',
    role: '2025级博士后',
    title: '博士后',
    category: 'postdoc',
    image: 'yanlijun.png',
    email: '',
    research: ['工业固废高值化利用'],
    bio: '2025级博士后，研究方向为工业固废高值化利用。2026年5月参加"2026固废资源化与生态材料高质量发展学术与技术交流会"并作口头报告。',
    education: [],
    courses: [],
    honors: []
  },
  {
    id: 'lisi',
    name: '李思',
    nameEn: 'Li Si',
    role: '2025级博士后',
    title: '博士后',
    category: 'postdoc',
    image: 'lisi.jpg',
    email: '',
    research: ['地下水有机污染物去除功能材料'],
    bio: '2025级博士后，研究方向为地下水有机污染物去除功能材料的设计制备及其在污染修复中的应用。',
    education: [],
    courses: [],
    honors: []
  },
  {
    id: 'huangwenfeng',
    name: '黄文锋',
    nameEn: 'Huang Wenfeng',
    role: '2022级博士研究生',
    title: '博士研究生',
    category: 'student',
    image: 'huangwenfeng.jpg',
    email: '',
    research: ['稻田土重金属生物地球化学'],
    bio: '2022级博士研究生，研究方向为稻田土重金属生物地球化学。2026年在 Environmental Science & Technology 发表关于有机质腐殖化调控水铁矿转化机制的研究论文。',
    education: [],
    courses: [],
    honors: []
  },
  {
    id: 'zhangzehong',
    name: '张泽宏',
    nameEn: 'Zhang Zehong',
    role: '2021级博士研究生',
    title: '博士研究生',
    category: 'student',
    image: 'zhangzehong.jpg',
    email: '',
    research: ['土壤光化学过程'],
    bio: '2021级博士研究生，研究方向为土壤光化学过程，关注自然条件下铬(VI)的光化学还原及铁硅酸盐络合机制。',
    education: [],
    courses: [],
    honors: []
  },
  {
    id: 'yuanchengpeng',
    name: '袁程鹏',
    nameEn: 'Yuan Chengpeng',
    role: '2023级博士研究生',
    title: '博士研究生',
    category: 'student',
    image: null,
    email: '',
    research: ['土壤有机碳'],
    bio: '2023级博士研究生，研究方向为土壤有机碳循环及其环境效应。',
    education: [],
    courses: [],
    honors: []
  },
  {
    id: 'zhaoruiji',
    name: '赵睿基',
    nameEn: 'Zhao Ruiji',
    role: '2025级博士研究生',
    title: '博士研究生',
    category: 'student',
    image: 'zhaoruiji.jpg',
    email: '',
    research: ['矿山土壤生物地球化学循环'],
    bio: '2025级博士研究生，研究方向为矿山土壤生物地球化学循环。',
    education: [],
    courses: [],
    honors: []
  },
  {
    id: 'yangtianhuan',
    name: '杨天寰',
    nameEn: 'Yang Tianhuan',
    role: '2025级博士研究生',
    title: '博士研究生',
    category: 'student',
    image: 'yangtianhuan.jpg',
    email: '',
    research: ['土壤环境毒理学'],
    bio: '2025级博士研究生，研究方向为土壤环境毒理学。',
    education: [],
    courses: [],
    honors: []
  },
  {
    id: 'liangyanping',
    name: '梁艳萍',
    nameEn: 'Liang Yanping',
    role: '2025级博士研究生',
    title: '博士研究生',
    category: 'student',
    image: 'liangyanping.jpg',
    email: '',
    research: ['土壤碳排放'],
    bio: '2025级博士研究生，研究方向为土壤碳排放及其调控机制。',
    education: [],
    courses: [],
    honors: []
  },
  {
    id: 'jizewen',
    name: '纪泽文',
    nameEn: 'Ji Zewen',
    role: '2024级博士研究生',
    title: '博士研究生',
    category: 'student',
    image: 'jizewen.jpg',
    email: '',
    research: ['环境毒理学'],
    bio: '2024级博士研究生，研究方向为环境毒理学。',
    education: [],
    courses: [],
    honors: []
  },
  {
    id: 'lixin',
    name: '李欣',
    nameEn: 'Li Xin',
    role: '2025级博士研究生',
    title: '博士研究生',
    category: 'student',
    image: 'lixin.jpg',
    email: '',
    research: ['土壤新污染物迁移转化'],
    bio: '2025级博士研究生，研究方向为土壤新污染物迁移转化。',
    education: [],
    courses: [],
    honors: []
  },
  {
    id: 'zhuping',
    name: '朱萍',
    nameEn: 'Zhu Ping',
    role: '2025级博士研究生',
    title: '博士研究生',
    category: 'student',
    image: 'zhuping.jpg',
    email: '',
    research: ['土壤重金属迁移转化'],
    bio: '2025级博士研究生，研究方向为土壤重金属迁移转化。',
    education: [],
    courses: [],
    honors: []
  },
  {
    id: 'wuyutong',
    name: '吴宇彤',
    nameEn: 'Wu Yutong',
    role: '2025级博士研究生',
    title: '博士研究生',
    category: 'student',
    image: null,
    email: '',
    research: ['环境毒理学'],
    bio: '2025级博士研究生，研究方向为环境毒理学。',
    education: [],
    courses: [],
    honors: []
  },
  {
    id: 'lijingming',
    name: '李景铭',
    nameEn: 'Li Jingming',
    role: '2024级博士研究生',
    title: '博士研究生',
    category: 'student',
    image: 'lijingming.jpg',
    email: '',
    research: ['土壤新污染物'],
    bio: '2024级博士研究生，研究方向为土壤新污染物。',
    education: [],
    courses: [],
    honors: []
  },
  {
    id: 'likewei',
    name: '李可唯',
    nameEn: 'Li Kewei',
    role: '2024级博士研究生',
    title: '博士研究生',
    category: 'student',
    image: null,
    email: '',
    research: ['铁的生物地球化学过程'],
    bio: '2024级博士研究生，研究方向为铁的生物地球化学过程。',
    education: [],
    courses: [],
    honors: []
  },
  {
    id: 'huzhanghao',
    name: '胡张昊',
    nameEn: 'Hu Zhanghao',
    role: '2026级博士研究生',
    title: '博士研究生',
    category: 'student',
    image: 'huzhanghao.jpg',
    email: '',
    research: ['土壤新污染物迁移转化'],
    bio: '2026级博士研究生，研究方向为土壤新污染物迁移转化。',
    education: [],
    courses: [],
    honors: []
  },
  {
    id: 'wuweijie',
    name: '吴炜杰',
    nameEn: 'Wu Weijie',
    role: '2025级硕士研究生',
    title: '硕士研究生',
    category: 'student',
    image: 'wuweijie.jpg',
    email: '',
    research: ['土壤重金属污染'],
    bio: '2025级硕士研究生，研究方向为土壤重金属污染。',
    education: [],
    courses: [],
    honors: []
  },
  {
    id: 'niujiaxin',
    name: '牛甲鑫',
    nameEn: 'Niu Jiaxin',
    role: '2025级硕士研究生',
    title: '硕士研究生',
    category: 'student',
    image: 'niujiaxin.jpg',
    email: '',
    research: ['土壤重金属污染'],
    bio: '2025级硕士研究生，研究方向为土壤重金属污染。',
    education: [],
    courses: [],
    honors: []
  },
  {
    id: 'feinanfang',
    name: '费南芳',
    nameEn: 'Fei Nanfang',
    role: '2025级硕士研究生',
    title: '硕士研究生',
    category: 'student',
    image: null,
    email: '',
    research: ['环境毒理学'],
    bio: '2025级硕士研究生，研究方向为环境毒理学。',
    education: [],
    courses: [],
    honors: []
  },
  {
    id: 'liuqi',
    name: '刘淇',
    nameEn: 'Liu Qi',
    role: '2024级硕士研究生',
    title: '硕士研究生',
    category: 'student',
    image: 'liuqi.jpg',
    email: '',
    research: ['土壤光化学'],
    bio: '2024级硕士研究生，研究方向为土壤光化学。',
    education: [],
    courses: [],
    honors: []
  },
  {
    id: 'panjiaoming',
    name: '潘教明',
    nameEn: 'Pan Jiaoming',
    role: '2024级硕士研究生',
    title: '硕士研究生',
    category: 'student',
    image: 'panjiaoming.jpg',
    email: '',
    research: ['微塑料污染'],
    bio: '2024级硕士研究生，研究方向为微塑料污染。',
    education: [],
    courses: [],
    honors: []
  },
  {
    id: 'shaolexin',
    name: '邵乐心',
    nameEn: 'Shao Lexin',
    role: '2024级硕士研究生',
    title: '硕士研究生',
    category: 'student',
    image: null,
    email: '',
    research: ['有机固废利用经济性与LCA分析'],
    bio: '2024级硕士研究生，研究方向为有机固废利用经济性与生命周期评价（LCA）分析。',
    education: [],
    courses: [],
    honors: []
  },
  {
    id: 'fuzhengyue',
    name: '傅正越',
    nameEn: 'Fu Zhengyue',
    role: '2025级硕士研究生',
    title: '硕士研究生',
    category: 'student',
    image: 'fuzhengyue.png',
    email: '',
    research: ['能源转型下土壤生态碳汇'],
    bio: '2025级硕士研究生，研究方向为能源转型下土壤生态碳汇。',
    education: [],
    courses: [],
    honors: []
  }
];

function getMemberById(id) {
  return TEAM_DATA.find(m => m.id === id);
}

function getMembersByCategory(category) {
  return TEAM_DATA.filter(m => m.category === category);
}

function getAvatarUrl(member) {
  if (member.image) {
    return 'images/team/' + member.image;
  }
  return null;
}
